[package]
name = "rusty-cricket"
version = "0.1.0"
authors = ["Om-Raj"]
edition = "April 2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
